### ISSUE TITLE
Missing support for Sphinx' "dirhtml" target

### ISSUE THREAD

**Issue by jodal** [michaeljones/sphinx-to-github#3]
Line 270 in sphinxtogithub.py disables sphinx-to-github for any other Sphinx targets than "html":

```
if app.builder.name != "html":
    return
```

I personally need support for the "dirhtml" target.

**Comment by michaeljones** [comment]
Hi, thanks for logging this. I don't have access to my github code right now, as I've just moved country without a computer for coding. I'll try to fix it as soon as I can, in the mean time I hope you are comfortable with changing the source yourself. 

Please feel free to fork and patch if you're inclined.

Michael

**Comment by michaeljones** [comment]
Fixed in:

http://github.com/michaeljones/sphinx-to-github/commit/cbcd86d886838e880e79b8ac7bcd9a4ab3202915

Thanks! Sorry it took so long.

Michael

**Comment by jodal** [comment]
Thanks! Now I have no excuse for not replacing my Makefile hack with sphinx-to-github :-)
