### ISSUE TITLE
NoDirectoriesError not being dealt with properly when used as a sphinx extension

### ISSUE THREAD

**Issue by jfhbrook** [michaeljones/sphinx-to-github#4]
Hi there!

sphinx-to-github runs perfectly well as a sphinx extension if there are _directories to process (ie, if there's a good reason to regenerate docs), but if sphinx is ran a second time, and doesn't generate the _directories again, the whole thing chokes:

[josh@pidgey sphinx-github-githook]$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.0b2
loading pickled environment... done
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.

```
Exception occurred:
  File "/home/josh/sphinx-github-githook/source/extensions/sphinxtogithub.py", line 217, in create_layout
    raise NoDirectoriesError()
NoDirectoriesError
The full traceback has been saved in /tmp/sphinx-err-hqGucV.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

I was able to haxx it away by not raising an error around line 217 or so:

```
if not underscore_directories:
       pass
       #raise NoDirectoriesError()
```

(muahaha), but obviously this is bad form. I'd fix it myself, but I really really don't know much of anything about sphinx (I've been using jekyll and the gh wiki for docs until very very recently.)

**Comment by michaeljones** [comment]
Hey,
Thanks for the report. I feel a bit foolish for not tying up this loose end before. I've forgotten if there are any particular problems that mean it is always worth doing a make clean and make again (which avoids this for obvious reasons) but I'm sure it can be handled more gracefully. 

I'll try to take a look at it this week. In the mean time I've glad you've found an acceptable work around :)

Cheers,
Michael

**Comment by jfhbrook** [comment]
Hah! Thanks.  Don't feel obligated to fix it on my account alone! I'm just glad someone tackled the problem of the sphinx/jekyll underscore thing to begin with. Thanks dawg!

**Comment by xim** [comment]
Haven't seen any obvious errors when skipping the test (deleting lines 216 and 217) or when running a return Layout([], [])

My fav is the last one.

**Comment by michaeljones** [comment]
Thank you for that, it seems I needed yet another reminder :)

I've commited a small patch to hopefully sort this out. It will print a message in verbose mode indicating there are no _directories to fix but otherwise just keep quiet and carry on! 

Cheers,
Michael
