### ISSUE TITLE
This is fantastic, it should be on PyPi. 

### ISSUE THREAD

**Issue by kennethreitz** [michaeljones/sphinx-to-github#5]
If you don't do it, I will :)

**Comment by thomasw** [comment]
Seconded. Someone should also buy you a beer.

**Comment by michaeljones** [comment]
Now that it is an issue a developer likes to have :)

Thank you guys, kind of you to take the time. 

I'm afraid I don't know much about putting anything on PyPI but if it isn't too hard I'll try to get it done next week. 

Cheers for the prompting,
Michael

**Comment by kennethreitz** [comment]
:D

Let me know if you need any assistance. It took me a while to figure out.

**Comment by michaeljones** [comment]
Hey, the registration was easy, thanks to winhamwr's work on the setup.py. As a package it is viewable here:

http://pypi.python.org/pypi/sphinxtogithub/1.0.0

The only issue is I don't think I can upload any distributions from behind my company's proxy/firewall.

I'll try to do it next week when my home internet connection gets sorted, though if you have a bit of time and want to help, I could add you as a maintainer and you could give it a shot? No other strings attached :)

Cheers
Michael

**Comment by kennethreitz** [comment]
Awesome! 

I'd love to upload it for you. My username on pypi is `kennethreitz`.

**Comment by michaeljones** [comment]
Wow, thanks for the speedy reply. I've added you on PyPI, please add whatever you feel is best. I was going to do tar.gz and zip, source and binary distributions but I don't know if that is the best idea or not!

Much appreciated!
Michael

**Comment by michaeljones** [comment]
HI Kenneth,

Thank you for uploading that version of Sphinx-to-github. Sorry for not noticing sooner! I thought it might email it something.

Cheers for the help,
Michael
